server:
  port: 8765
spring:
  application:
    name: customer
  datasource:
    url: jdbc:mysql://localhost:3306/contract_tester
    password: password
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true