server:
  port: 8080
spring:
  application:
    name: customer
#  datasource:
#    password: password
#    url: jdbc:postgresql://localhost:5432/customer
#    username: sharan
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    password: password
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true